/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mariadbconnect4um;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author france
 */
public class Main extends javax.swing.JFrame {   
    ArrayList<String> table;
    GestDBmyLiteSwing objDB;
    DefaultTableModel model,model2;
    ExcelExport exp;
    int riga;//conta righe della tabella model2
    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        model=(DefaultTableModel) tblView.getModel();
        model2=(DefaultTableModel) tblNomi.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnect = new javax.swing.JButton();
        jtp = new javax.swing.JTabbedPane();
        pnlCatalogs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCat = new javax.swing.JList<>();
        lblCat = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNomi = new javax.swing.JTable();
        lblTab = new javax.swing.JLabel();
        pnlDati = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        cbxTabelle = new javax.swing.JComboBox<>();
        btnDownload = new javax.swing.JButton();
        lblConn = new javax.swing.JLabel();
        btnViewTab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MariaDBConnect");
        setLocation(new java.awt.Point(100, 100));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));
        setType(java.awt.Window.Type.UTILITY);

        btnConnect.setFont(new java.awt.Font("Ubuntu", 3, 17)); // NOI18N
        btnConnect.setText("Connect");
        btnConnect.setAlignmentX(0.5F);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jtp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtp.setAutoscrolls(true);
        jtp.setEnabled(false);
        jtp.setOpaque(true);

        lstCat.setFont(new java.awt.Font("Ubuntu", 3, 17)); // NOI18N
        lstCat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCat.setToolTipText("Selezionare il Catalogo cliccando sul nome");
        lstCat.setEnabled(false);
        lstCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCat);

        lblCat.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCat.setText("Catalogo Database");
        lblCat.setEnabled(false);

        tblNomi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNomi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Tabella", "Nome Tabella", "Nome Tabella"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblNomi.setShowGrid(true);
        jScrollPane4.setViewportView(tblNomi);

        lblTab.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTab.setText("Tabelle Catalogo: ");
        lblTab.setEnabled(false);

        javax.swing.GroupLayout pnlCatalogsLayout = new javax.swing.GroupLayout(pnlCatalogs);
        pnlCatalogs.setLayout(pnlCatalogsLayout);
        pnlCatalogsLayout.setHorizontalGroup(
            pnlCatalogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCatalogsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCatalogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(lblCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCatalogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addComponent(lblTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCatalogsLayout.setVerticalGroup(
            pnlCatalogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCatalogsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCatalogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCat)
                    .addComponent(lblTab))
                .addGap(18, 18, 18)
                .addGroup(pnlCatalogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jtp.addTab("Catalogs DB", pnlCatalogs);

        tblView.setAutoCreateRowSorter(true);
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblView.setCellSelectionEnabled(true);
        tblView.setShowGrid(true);
        jScrollPane2.setViewportView(tblView);

        javax.swing.GroupLayout pnlDatiLayout = new javax.swing.GroupLayout(pnlDati);
        pnlDati.setLayout(pnlDatiLayout);
        pnlDatiLayout.setHorizontalGroup(
            pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDatiLayout.setVerticalGroup(
            pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jtp.addTab("Selected Table", pnlDati);

        btnExit.setFont(new java.awt.Font("Ubuntu", 3, 17)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cbxTabelle.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cbxTabelle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cbxTabelle.setEnabled(false);
        cbxTabelle.setName(""); // NOI18N

        btnDownload.setFont(new java.awt.Font("Ubuntu", 3, 17)); // NOI18N
        btnDownload.setText("Download Table");
        btnDownload.setEnabled(false);
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        lblConn.setBackground(new java.awt.Color(255, 0, 0));
        lblConn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblConn.setForeground(new java.awt.Color(255, 255, 0));
        lblConn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConn.setText("0");
        lblConn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblConn.setOpaque(true);

        btnViewTab.setFont(new java.awt.Font("Ubuntu", 3, 17)); // NOI18N
        btnViewTab.setText("View Table");
        btnViewTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTabelle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewTab, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTabelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtp)
                .addGap(8, 8, 8))
        );

        jtp.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        String pp[]=new String[3];int i=0;
        do{
            pp[0]=JOptionPane.showInputDialog("Autenticazione:\n Inserire username");
            //pp[1]=JOptionPane.showInputDialog("Autenticazione:\n Inserire password");
            //pp[2]=JOptionPane.showInputDialog("Inserisci nome Database");
            objDB=new GestDBmyLiteSwing("UsrSardegna",pp[0],pp[0]+"@20");
            i++;
        }
        while (!objDB.ctrlDB().equalsIgnoreCase("ok")&& i<3);
        if(i>=3){
            JOptionPane.showMessageDialog(this, "Inserimento effettuato troppe volte! Arrivederci");
            System.exit(1);
        }
        btnConnect.setEnabled(false);
        lblConn.setBackground(Color.green);
        lblConn.setText("1");
        jtp.setEnabled(true);
        try {
            lstCat.setListData(objDB.getCatalogMetadata());
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblCat.setEnabled(true);
        lstCat.setEnabled(true);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        exp = new ExcelExport();
        String tmp="Errore";
        try {
            tmp=exp.exportTable(tblView, new File(cbxTabelle.getSelectedItem()+".xlsx"));
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "File "+tmp+" generato");
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void lstCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCatMouseClicked
        objDB.setNomeDB(lstCat.getSelectedValue());
        lblTab.setText("Tabelle Catalogo "+lstCat.getSelectedValue());
        try {
            table=objDB.getTablesMetadata();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbxTabelle.removeAllItems();
        cbxTabelle.addItem("Select");
        riga=0;
        model2.setRowCount(0);//cancella tabella
        model2.setRowCount(riga + 1); //nuova riga
        int c=1;
        for(String s:table){
            cbxTabelle.addItem(s);
            model2.setValueAt(s, riga, c-1);   
            if(c%3==0){
                riga++; c=1;
                model2.setRowCount(riga + 1); //nuova riga 
                }
            else
                c++;
        }
        try {
            objDB.closeRs();
            objDB.closeConn();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbxTabelle.setEnabled(true);
    }//GEN-LAST:event_lstCatMouseClicked

    private void btnViewTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTabActionPerformed
        model.setRowCount(0);//cancella tabella
        objDB.dirQuery("SELECT * FROM "+cbxTabelle.getSelectedItem());
        btnDownload.setEnabled(true);
        try {
            objDB.tabella(model);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtp.setSelectedIndex(1);
    }//GEN-LAST:event_btnViewTabActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnViewTab;
    private javax.swing.JComboBox<String> cbxTabelle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jtp;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblConn;
    private javax.swing.JLabel lblTab;
    private javax.swing.JList<String> lstCat;
    private javax.swing.JPanel pnlCatalogs;
    private javax.swing.JPanel pnlDati;
    private javax.swing.JTable tblNomi;
    private javax.swing.JTable tblView;
    // End of variables declaration//GEN-END:variables
}
